version: "3.8"
services:
  api:
    image: 123698967521.dkr.ecr.us-east-2.amazonaws.com/docker_study
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "5000:5000"
